window.Cards = [{
  "title": "赤壁の戦い",
  "happened": 2080000,
  "flavorText": "風が吹いてくるよお",
  "tags": "歴史"
}, {
  "title": "古代ローマ帝国東西分裂",
  "happened": 3950000,
  "flavorText": "詳しくは教養西洋史講座第30回へ",
  "tags": "歴史"
}, {
  "title": "十七条の憲法制定",
  "happened": 6040000,
  "flavorText": "和をもって尊しとなすらしい",
  "tags": "日本史"
}, {
  "title": "足利尊氏　生誕",
  "happened": 13050818,
  "flavorText": "初代征夷大将軍",
  "tags": ""
}, {
  "title": "オランダ東インド会社設立",
  "happened": 16020000,
  "flavorText": "業務内容が一切分からない社名",
  "tags": ""
}, {
  "title": "ゴリラが人類によって発見される",
  "happened": 18740000,
  "flavorText": "うほうほ",
  "tags": "ゴリラ"
}, {
  "title": "ベルが電話の実験に成功",
  "happened": 18760310,
  "flavorText": "ワトソン君、用事がある、ちょっと来てくれたまえ",
  "tags": ""
}, {
  "title": "切り裂きジャック初犯行",
  "happened": 18880831,
  "flavorText": "ハート見せちゃおっかな～",
  "tags": "事件"
}, {
  "title": "任天堂が創業した年",
  "happened": 18890000,
  "flavorText": "実は老舗企業",
  "tags": ""
}, {
  "title": "きんさんぎんさん生誕",
  "happened": 18920801,
  "flavorText": "きんは100歳100歳、ぎんも100歳100歳。ダスキン呼ぶなら100番100番。",
  "tags": ""
}, {
  "title": "タイタニック号沈没事故",
  "happened": 19120415,
  "flavorText": "氷山強い",
  "tags": ""
}, {
  "title": "第一回アカデミー賞授賞式",
  "happened": 19290516,
  "flavorText": "世界的な映画の祭典",
  "tags": "映画"
}, {
  "title": "広島市への原子爆弾投下",
  "happened": 19450806,
  "flavorText": "いっぱい死んじゃった",
  "tags": "歴史"
}, {
  "title": "初代ゴジラ公開",
  "happened": 19541103,
  "flavorText": "怪獣王の誕生",
  "tags": ""
}, {
  "title": "ディズニーランド開園",
  "happened": 19550717,
  "flavorText": "アメリカカリフォルニアに最初のディズニーランド開園",
  "tags": ""
}, {
  "title": "東京タワー完成",
  "happened": 19581223,
  "flavorText": "333メートル！",
  "tags": ""
}, {
  "title": "オランジーナ社設立",
  "happened": 19620000,
  "flavorText": "サントリーに買収されちゃったね",
  "tags": ""
}, {
  "title": "ビートルズが初来日",
  "happened": 19660629,
  "flavorText": "史上初の武道館ライブ",
  "tags": "芸能 音楽"
}, {
  "title": "人類初の月面着陸",
  "happened": 19690720,
  "flavorText": "小さな一歩",
  "tags": ""
}, {
  "title": "マクドナルド日本1号店が開店",
  "happened": 19710720,
  "flavorText": "おいしい",
  "tags": ""
}, {
  "title": "あさま山荘事件",
  "happened": 19720219,
  "flavorText": "浅間山荘において連合赤軍が人質をとって立てこもった事件",
  "tags": "事件"
}, {
  "title": "ポテトチップス発売",
  "happened": 19750000,
  "flavorText": "みんな大好き",
  "tags": ""
}, {
  "title": "コミックマーケット初開催",
  "happened": 19751221,
  "flavorText": "虎ノ門日本消防会館会議室",
  "tags": ""
}, {
  "title": "機動戦士ガンダム放送開始",
  "happened": 19790407,
  "flavorText": "行きまーす",
  "tags": "アニメ"
}, {
  "title": "ボブ・マーリー死没",
  "happened": 19810511,
  "flavorText": "onelove",
  "tags": ""
}, {
  "title": "ジーコ初来日",
  "happened": 19811213,
  "flavorText": "すごい人",
  "tags": "サッカー"
}, {
  "title": "五百円玉発行開始",
  "happened": 19820000,
  "flavorText": "私の一番好きな硬貨",
  "tags": "貨幣"
}, {
  "title": "JT設立",
  "happened": 19850401,
  "flavorText": "喫煙は、あなたにとって肺がんの原因の一つとなります。疫学的な推計によると、喫煙者は肺がんにより死亡する危険性が非喫煙者に比べて約2倍から4倍高くなります。",
  "tags": ""
}, {
  "title": "豊田商事会長刺殺事件",
  "happened": 19850618,
  "flavorText": "マスコミの前で刺される",
  "tags": "日本の事件"
}, {
  "title": "ドラゴンクエスト発売",
  "happened": 19860527,
  "flavorText": "うれしい",
  "tags": "ゲーム"
}, {
  "title": "日本で消費税導入",
  "happened": 19890401,
  "flavorText": "いやだね",
  "tags": ""
}, {
  "title": "日本で初代ゲームボーイ発売",
  "happened": 19890421,
  "flavorText": "発売当時のメーカー希望小売価格は12,500円（税込)",
  "tags": ""
}, {
  "title": "「ダウンタウンのガキの使いやあらへんで！」スタート",
  "happened": 19891004,
  "flavorText": "DTGT",
  "tags": ""
}, {
  "title": "スーパーファミコン発売",
  "happened": 19901121,
  "flavorText": "すごーい",
  "tags": ""
}, {
  "title": "千代の富士引退",
  "happened": 19910514,
  "flavorText": "体力の限界",
  "tags": "相撲"
}, {
  "title": "ベルリンの壁崩壊",
  "happened": 19911109,
  "flavorText": "よかったね",
  "tags": "歴史"
}, {
  "title": "ソビエト連邦が解体",
  "happened": 19911225,
  "flavorText": "どっかーん",
  "tags": "歴史"
}, {
  "title": "道の駅誕生",
  "happened": 19930422,
  "flavorText": "第1号103箇所",
  "tags": ""
}, {
  "title": "阪神・淡路大震災",
  "happened": 19950117,
  "flavorText": "いっぱい死んだ",
  "tags": ""
}, {
  "title": "地下鉄サリン事件",
  "happened": 19950320,
  "flavorText": "しょーこー",
  "tags": "事件"
}, {
  "title": "羽生善治が史上初将棋７冠独占",
  "happened": 19960000,
  "flavorText": "しゅごい",
  "tags": ""
}, {
  "title": "Java 1.0 リリース",
  "happened": 19960000,
  "flavorText": "Write once, run anywhere",
  "tags": ""
}, {
  "title": "ポケットモンスター赤緑 発売日",
  "happened": 19960227,
  "flavorText": "やったー",
  "tags": "げーむ"
}, {
  "title": "たまごっち発売",
  "happened": 19961123,
  "flavorText": "バカ売れしたおもちゃ",
  "tags": ""
}, {
  "title": "日本の消費税が5%に増税",
  "happened": 19970401,
  "flavorText": "いやんなっちゃうね",
  "tags": ""
}, {
  "title": "ONE PIECE連載開始",
  "happened": 19970722,
  "flavorText": "全部置いてきた",
  "tags": "漫画"
}, {
  "title": "ポケモンのアニメでポリゴンショック",
  "happened": 19971216,
  "flavorText": "テレビを見る時は",
  "tags": "アニメ"
}, {
  "title": "長野オリンピック開催",
  "happened": 19980207,
  "flavorText": "20世紀最後の冬季オリンピック",
  "tags": ""
}, {
  "title": "X JAPANのhideが死去",
  "happened": 19980502,
  "flavorText": "悲しいよぉ",
  "tags": ""
}, {
  "title": "宇多田ヒカルデビュー",
  "happened": 19981209,
  "flavorText": "母は藤圭子",
  "tags": ""
}, {
  "title": "2ちゃんねる開設",
  "happened": 19990530,
  "flavorText": "匿名掲示板",
  "tags": ""
}, {
  "title": "奥井雅美「only one, No.1」発売",
  "happened": 19991203,
  "flavorText": "通算19作目のシングル",
  "tags": "音楽"
}, {
  "title": "プレイステーション２発売",
  "happened": 20000304,
  "flavorText": "神ハード",
  "tags": "ゲーム"
}, {
  "title": "二千円紙幣の発行",
  "happened": 20000719,
  "flavorText": "すでに製造中止",
  "tags": ""
}, {
  "title": "USJ開園",
  "happened": 20010331,
  "flavorText": "近年好調",
  "tags": ""
}, {
  "title": "映画「千と千尋の神隠し」日本での公開日",
  "happened": 20010720,
  "flavorText": "小学生でも働いてるのにね",
  "tags": "映画"
}, {
  "title": "アメリカ同時多発テロ事件",
  "happened": 20010911,
  "flavorText": "人がいっぱい死んだ",
  "tags": ""
}, {
  "title": "ブルーレイディスクの規格発表",
  "happened": 20020219,
  "flavorText": "やっぱりソニーがナンバーワン",
  "tags": ""
}, {
  "title": "多摩川にアゴヒゲアザラシの「タマちゃん」出現",
  "happened": 20020807,
  "flavorText": "タマちゃんを見守る会",
  "tags": ""
}, {
  "title": "ソニン「カレーライスの女」発売",
  "happened": 20020821,
  "flavorText": "わかってますわかってます",
  "tags": "音楽"
}, {
  "title": "ヨン様ブーム",
  "happened": 20030000,
  "flavorText": "老後の過ち",
  "tags": "ブーム"
}, {
  "title": "SMAP「世界にひとつだけの花」発売",
  "happened": 20030305,
  "flavorText": "意外と古いよね",
  "tags": "芸能"
}, {
  "title": "モンスターハンター発売",
  "happened": 20040311,
  "flavorText": "上手に焼けました",
  "tags": ""
}, {
  "title": "千円紙幣が野口英世に変更",
  "happened": 20041101,
  "flavorText": "医者らしい",
  "tags": ""
}, {
  "title": "Youtubeに初めて動画が投稿された日",
  "happened": 20050215,
  "flavorText": "動物園で撮影",
  "tags": ""
}, {
  "title": "アーケード「THE IDOLM@STER」稼働",
  "happened": 20050726,
  "flavorText": "貧乳地雷女",
  "tags": "ゲーム"
}, {
  "title": "トリノ冬季オリンピック開催",
  "happened": 20060210,
  "flavorText": "荒川静香がイナバウワーで金とったやつ",
  "tags": ""
}, {
  "title": "Twitterサービス開始",
  "happened": 20060715,
  "flavorText": "最近はママ活が流行ってます",
  "tags": ""
}, {
  "title": "太陽系第9惑星消滅",
  "happened": 20060825,
  "flavorText": "勝手なもんやで",
  "tags": "宇宙"
}, {
  "title": "最初のiPhone発売",
  "happened": 20070629,
  "flavorText": "みんなが待っていたiPhone、ついに登場。",
  "tags": ""
}, {
  "title": "初音ミク発売",
  "happened": 20070831,
  "flavorText": "ミクだよ～",
  "tags": "インターネット"
}, {
  "title": "草彅剛　泥酔事件",
  "happened": 20090423,
  "flavorText": "しんごーしんごー",
  "tags": "全裸"
}, {
  "title": "バンクーバーオリンピック開会式",
  "happened": 20100212,
  "flavorText": "反省してまーす",
  "tags": "カナダ"
}, {
  "title": "アウトレイジ公開",
  "happened": 20100612,
  "flavorText": "全員悪人",
  "tags": "映画"
}, {
  "title": "ハドソン解散",
  "happened": 20120000,
  "flavorText": "バイバイハドソン",
  "tags": "ゲーム"
}, {
  "title": "東京事変解散",
  "happened": 20120229,
  "flavorText": "最後の曲は透明人間",
  "tags": "音楽"
}, {
  "title": "王将社長射殺事件",
  "happened": 20131219,
  "flavorText": "４発も撃たれた",
  "tags": "事件"
}, {
  "title": "「森田一義アワー 笑っていいとも!」放送終了",
  "happened": 20140331,
  "flavorText": "終わっちゃった",
  "tags": ""
}, {
  "title": "野々村 竜太郎号泣会見",
  "happened": 20140701,
  "flavorText": "一瞬世界で注目を浴びた歴史的会見",
  "tags": ""
}, {
  "title": "ハリウッドザコシショウ R1優勝",
  "happened": 20160306,
  "flavorText": "ハンマーカンマー",
  "tags": ""
}, {
  "title": "吉澤ひとみ飲酒ひき逃げ",
  "happened": 20180906,
  "flavorText": "よっすぃー…",
  "tags": "事件"
}, {
  "title": "WWW 実装",
  "happened": 19901113,
  "flavorText": "最初は陰キャの溜まり場だった",
  "tags": "インターネット"
}, {
  "title": "地下鉄サリン事件",
  "happened": 19950320,
  "flavorText": "修行するぞ修行するぞ修行するぞ",
  "tags": ""
}, {
  "title": "マイケル・ジャクソン死去",
  "happened": 20090625,
  "flavorText": "；ー；",
  "tags": ""
}, {
  "title": "ハリー・ポッターと賢者の石 英国で発売",
  "happened": 19970626,
  "flavorText": "英国では日本より2年早く発売されました",
  "tags": "ハリー・ポッター 小説"
}, {
  "title": "アナログ放送終了",
  "happened": 20120331,
  "flavorText": "地デジカ",
  "tags": ""
}, {
  "title": "キズナアイ活動開始",
  "happened": 20161201,
  "flavorText": "Vtuber時代開幕",
  "tags": "インターネット"
}, {
  "title": "東日本大震災",
  "happened": 20110311,
  "flavorText": "悲しいね",
  "tags": ""
}, {
  "title": "キズナアイ生誕",
  "happened": 20170630,
  "flavorText": "Vtuberの王",
  "tags": ""
}];